spring:
  application:
    name: crm
    
  datasource:
    #H2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/crmdb;DB_CLOSE_ON_EXIT=FALSE
    
  devtools:
    add-properties: false
  
  h2:
    console:
      enabled: true
      path: /console
  
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect